# Generated by Django 5.2.4 on 2026-02-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_module_options_studentprogress_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_expiry_minutes', models.IntegerField(default=10, help_text='Token expiry time in minutes')),
                ('heartbeat_interval_seconds', models.IntegerField(default=10, help_text='Heartbeat interval in seconds')),
                ('max_micro_quiz_failures', models.IntegerField(default=3, help_text='Maximum micro-quiz failures allowed')),
                ('certificate_signer_name', models.CharField(default='LearnTrust Administrator', help_text='Default certificate signer name', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='allowed_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='disable_fast_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='disable_seeking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='mandatory_checkpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='must_pass_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='required_replays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='timeout_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='event_type',
            field=models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('heartbeat', 'Heartbeat'), ('checkpoint', 'Checkpoint')], default='play', max_length=20),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='token_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='watchevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchevent',
            unique_together={('student', 'module', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='watchevent',
            index=models.Index(fields=['student', 'module', 'created_at'], name='student_wat_student_295353_idx'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
