# Generated by Django 5.2.4 on 2026-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_course_moodle_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='hls_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
