# Generated by Django 6.0.1 on 2026-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
