# Generated by Django 5.2.4 on 2026-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_systemsettings_certificate_is_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='moodle_user_id',
            field=models.IntegerField(blank=True, help_text='Moodle user ID for API integration', null=True),
        ),
    ]
