# Generated by Django 5.2.4 on 2026-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile_moodle_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='watchevent',
            name='event_type',
            field=models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('heartbeat', 'Heartbeat'), ('checkpoint', 'Checkpoint'), ('webcam_snapshot', 'Webcam Snapshot')], default='play', max_length=20),
        ),
    ]
