# Generated by Django 6.0.1 on 2026-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_teacherregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moodle_course_id',
            field=models.IntegerField(blank=True, help_text='Moodle course ID for API integration', null=True),
        ),
    ]
